name: Build

on:
  push:
    branches:
      - master

jobs:
  run-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_score_bot_db
          POSTGRES_PASSWORD: adminadmin
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: adminadmin
      DB_HOSTNAME: 127.0.0.1
      DB_PORT: 5432
      LOG_LEVEL: 'INFO'
    steps:
      - uses: actions/checkout@v2
      - name: User node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies and run tests
        run: |
          yarn install
          yarn test
      - name: generate readme commands and commit
        continue-on-error: true
        run: |
          yarn generate-readme
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git commit -m "Generate new README based on commands manifest." README.md
      - name: Push README.md
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
      - name: build and publish docker container
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          docker build . -t ryanpage/discord-score-bot:${{ github.run_number }} -t ryanpage/discord-score-bot:latest
          docker push ryanpage/discord-score-bot:${{ github.run_number }}
          docker push ryanpage/discord-score-bot:latest
      - name: redeploy bot
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}